/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author KIIT
 */
import java.util.Date;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import com.sun.jdi.connect.spi.Connection;
import java.beans.Statement;
import java.io.IOException;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
//import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.*;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Action;
import javax.swing.Timer;
import java.awt.Color;
public class newstudent extends javax.swing.JFrame {

	/**
	 * Creates new form newstudent
	 */
	public newstudent() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                jSeparator1 = new javax.swing.JSeparator();
                jLabel3 = new javax.swing.JLabel();
                jLabel4 = new javax.swing.JLabel();
                jLabel5 = new javax.swing.JLabel();
                jLabel6 = new javax.swing.JLabel();
                jLabel7 = new javax.swing.JLabel();
                jTextField1 = new javax.swing.JTextField();
                jTextField2 = new javax.swing.JTextField();
                jTextField3 = new javax.swing.JTextField();
                jTextField4 = new javax.swing.JTextField();
                jComboBox1 = new javax.swing.JComboBox<>();
                jButton1 = new javax.swing.JButton();
                jButton2 = new javax.swing.JButton();
                jButton3 = new javax.swing.JButton();
                jLabel8 = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setLocation(new java.awt.Point(380, 150));
                setUndecorated(true);
                getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bms/New buyer ani.gif"))); // NOI18N
                getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 28, -1, -1));

                jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bms/new buyer.png"))); // NOI18N
                getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 28, -1, -1));
                getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 100, 588, 10));

                jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                jLabel3.setText("Name");
                getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 150, -1, -1));

                jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                jLabel4.setText("Contact");
                getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 211, -1, -1));

                jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                jLabel5.setText("Address");
                getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 275, -1, -1));

                jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                jLabel6.setText("Email");
                getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 335, -1, -1));

                jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                jLabel7.setText("Gender");
                getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 386, -1, -1));

                jTextField1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                jTextField1.setForeground(new java.awt.Color(153, 153, 153));
                jTextField1.setText("Enter Name");
                jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
                        public void focusGained(java.awt.event.FocusEvent evt) {
                                jTextField1FocusGained(evt);
                        }
                        public void focusLost(java.awt.event.FocusEvent evt) {
                                jTextField1FocusLost(evt);
                        }
                });
                getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 147, 157, -1));

                jTextField2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                jTextField2.setForeground(new java.awt.Color(153, 153, 153));
                jTextField2.setText("Contact Number");
                jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
                        public void focusGained(java.awt.event.FocusEvent evt) {
                                jTextField2FocusGained(evt);
                        }
                        public void focusLost(java.awt.event.FocusEvent evt) {
                                jTextField2FocusLost(evt);
                        }
                });
                getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 208, 157, -1));

                jTextField3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                jTextField3.setForeground(new java.awt.Color(153, 153, 153));
                jTextField3.setText("Enter Address");
                jTextField3.addFocusListener(new java.awt.event.FocusAdapter() {
                        public void focusGained(java.awt.event.FocusEvent evt) {
                                jTextField3FocusGained(evt);
                        }
                        public void focusLost(java.awt.event.FocusEvent evt) {
                                jTextField3FocusLost(evt);
                        }
                });
                getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 272, 157, -1));

                jTextField4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                jTextField4.setForeground(new java.awt.Color(153, 153, 153));
                jTextField4.setText("Enter Email");
                jTextField4.addFocusListener(new java.awt.event.FocusAdapter() {
                        public void focusGained(java.awt.event.FocusEvent evt) {
                                jTextField4FocusGained(evt);
                        }
                        public void focusLost(java.awt.event.FocusEvent evt) {
                                jTextField4FocusLost(evt);
                        }
                });
                getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 332, 157, -1));

                jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other", " " }));
                getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 383, 157, -1));

                jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bms/save.png"))); // NOI18N
                jButton1.setText("Save\n");
                jButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton1ActionPerformed(evt);
                        }
                });
                getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 423, -1, -1));

                jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bms/Reset.png"))); // NOI18N
                jButton2.setText("Reset\n");
                jButton2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton2ActionPerformed(evt);
                        }
                });
                getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 423, -1, -1));

                jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bms/close Jframe.png"))); // NOI18N
                jButton3.setText("Close");
                jButton3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton3ActionPerformed(evt);
                        }
                });
                getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 423, -1, -1));

                jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bms/all page background image.png"))); // NOI18N
                getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 650, 500));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
                // TODO add your handling code here:
		if (jTextField1.getText().equals("Enter Name"))
		{
			jTextField1.setText("");
			//jTextField1.setForeground(Color(0,0,0));
		}
        }//GEN-LAST:event_jTextField1FocusGained

        private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
                // TODO add your handling code here:
		if (jTextField1.getText().equals(""))
		{
			jTextField1.setText("Enter Name");
			//jTextField1.setForeground(Color(153,153,153));
			jTextField1.setForeground(Color.GRAY);
		}
        }//GEN-LAST:event_jTextField1FocusLost

        private void jTextField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusGained
                // TODO add your handling code here:
		if (jTextField2.getText().equals("Contact Number"))
		{
			jTextField2.setText("");
			jTextField2.setForeground(Color.GRAY);
		}
        }//GEN-LAST:event_jTextField2FocusGained

        private void jTextField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusLost
                // TODO add your handling code here:
		if (jTextField2.getText().equals(""))
		{
			jTextField2.setText("Contact Number");
			jTextField2.setForeground(Color.GRAY);
		}
        }//GEN-LAST:event_jTextField2FocusLost

        private void jTextField3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3FocusGained
                // TODO add your handling code here:
		if (jTextField3.getText().equals("Enter Address"))
		{
			jTextField3.setText("");
			jTextField3.setForeground(Color.GRAY);
		}
        }//GEN-LAST:event_jTextField3FocusGained

        private void jTextField3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3FocusLost
                // TODO add your handling code here:
		if (jTextField3.getText().equals(""))
		{
			jTextField3.setText("Enter Address");
			jTextField3.setForeground(Color.gray);
		}
        }//GEN-LAST:event_jTextField3FocusLost

        private void jTextField4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField4FocusGained
                // TODO add your handling code here:
			if (jTextField4.getText().equals("Enter Email"))
		{
			jTextField4.setText("");
			jTextField4.setForeground(Color.gray);
		}
        }//GEN-LAST:event_jTextField4FocusGained

        private void jTextField4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField4FocusLost
                // TODO add your handling code here:
		if (jTextField4.getText().equals(""))
		{
			jTextField4.setText("Enter Email");
			jTextField4.setForeground(Color.gray);
		}
        }//GEN-LAST:event_jTextField4FocusLost

        private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
                // TODO add your handling code here:
		setVisible(false);
        }//GEN-LAST:event_jButton3ActionPerformed

        private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                // TODO add your handling code here:
		setVisible(false);
		newstudent ns=new newstudent();
		ns.setVisible(true);
        }//GEN-LAST:event_jButton2ActionPerformed
public Connection con;
        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                // TODO add your handling code here:
		String name=jTextField1.getText();
		String contact=jTextField2.getText();
		String address=jTextField3.getText();
		String email=jTextField4.getText();
		String gender=(String)jComboBox1.getSelectedItem();
		String query="insert into newstudent(name,contact,address,email,gender) values(?,?,?,?,?)";
		try{
		Class.forName("com.mysql.cj.jdbc.Driver");
		java.sql.Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/mysql6","root","i1love2my3brother@");
		PreparedStatement pst = con.prepareStatement(query);
		pst.setString(1, name);
		pst.setString(2, contact);
		pst.setString(3, address);
		pst.setString(4, email);
		pst.setString(5, gender);
		pst.executeUpdate();
		JOptionPane.showMessageDialog(null,"Successfully updated");
		setVisible(false);
		newstudent ns=new newstudent();
		ns.setVisible(true);
		}
		catch(Exception e)
		{
			JOptionPane.showMessageDialog(null,e);	
		}
        }//GEN-LAST:event_jButton1ActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(newstudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(newstudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(newstudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(newstudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new newstudent().setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton jButton1;
        private javax.swing.JButton jButton2;
        private javax.swing.JButton jButton3;
        private javax.swing.JComboBox<String> jComboBox1;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JSeparator jSeparator1;
        private javax.swing.JTextField jTextField1;
        private javax.swing.JTextField jTextField2;
        private javax.swing.JTextField jTextField3;
        private javax.swing.JTextField jTextField4;
        // End of variables declaration//GEN-END:variables

	private Color Color(int i, int i0, int i1) {
		return null;
	}}
	

